nodes:
- id: x
  params:
    input_index: 0
  type: Input
- id: y
  params:
    input_index: 1
  type: Input
- id: sum
  params:
    inputs:
    - x
    - y
  type: Add
- id: factor
  params:
    value: 2.0
  type: Constant
- id: result
  params:
    inputs:
    - sum
    - factor
  type: Multiply
outputs:
- result
trigger: sum
