nodes:
- id: input_7
  params:
    input_index: 0
  type: Input
- id: input_8
  params:
    input_index: 1
  type: Input
- id: input_9
  params:
    input_index: 2
  type: Input
- id: sum_10
  params:
    inputs:
    - input_7
    - input_8
    - input_9
  type: Sum
- id: const_11
  params:
    value: 3.0
  type: Constant
- id: mul_13
  params:
    inputs:
    - sum_10
    - const_12
  type: Multiply
- id: const_16
  params:
    value: 0.3333333333333333
  type: Constant
- id: const_14
  params:
    value: 25.0
  type: Constant
- id: cmp_15
  params:
    inputs:
    - mul_13
    - const_14
    op: GreaterThan
  type: Comparison
outputs:
- mul_13
trigger: cmp_15
