// This file defines the Python-visible node classes
// These are generated by the derive macro, but we need to ensure
// they're properly accessible

use pyo3::prelude::*;

// The derive macro generates these, but we need the definitions here
// for the Graph methods to work properly

#[pyclass]
pub struct Input {
    #[pyo3(get)]
    pub id: String,
    #[pyo3(get)]
    pub name: String,
}

#[pyclass]
pub struct Const {
    #[pyo3(get)]
    pub id: String,
    #[pyo3(get)]
    pub value: f64,
}

#[pyclass]
pub struct Add {
    #[pyo3(get)]
    pub id: String,
    #[pyo3(get)]
    pub children: Vec<PyObject>,
}

#[pyclass]
pub struct Mul {
    #[pyo3(get)]
    pub id: String,
    #[pyo3(get)]
    pub children: Vec<PyObject>,
}

#[pyclass]
pub struct Div {
    #[pyo3(get)]
    pub id: String,
    #[pyo3(get)]
    pub left: PyObject,
    #[pyo3(get)]
    pub right: PyObject,
}